# Generated by Django 3.1.14 on 2024-06-24 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название')),
                ('image', models.ImageField(upload_to='', verbose_name='картинка')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='название(анг.)')),
                ('title_jp', models.CharField(blank=True, max_length=200, verbose_name='название(яп.)')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('previous_evolution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_evolutions', to='pokemon_entities.pokemon', verbose_name='предыдущая эволюция')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(verbose_name='широта')),
                ('lon', models.FloatField(verbose_name='долгота')),
                ('appeared_at', models.DateTimeField(blank=True, null=True, verbose_name='появится')),
                ('disappeared_at', models.DateTimeField(blank=True, null=True, verbose_name='пропадет')),
                ('level', models.IntegerField(blank=True, null=True, verbose_name='уровень')),
                ('health', models.IntegerField(blank=True, null=True, verbose_name='здоровье')),
                ('strenght', models.IntegerField(blank=True, null=True, verbose_name='атака')),
                ('defence', models.IntegerField(blank=True, null=True, verbose_name='защита')),
                ('stamina', models.IntegerField(blank=True, null=True, verbose_name='выносливость')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_entities', to='pokemon_entities.pokemon', verbose_name='покемон')),
            ],
        ),
    ]
